add platform to config and option to ignore optical dedup; fix issue #15
vdblab/vdblab-shotgun pull request #19
Opened 2022-12-20 19:34 UTC by nickp60

2022-12-20 22:44 UTC, funnell requested changes

2022-12-20 22:44 UTC, funnell commented on config/config.yaml
> +dedup_platform: "HiSeq"
what do you think about forcing users to set something for platform?

2022-12-20 22:44 UTC, funnell commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
platform version numbers aren't a valid input

2022-12-20 22:44 UTC, funnell commented on workflow/rules/preprocess.smk
> +            ordered \
:)

2022-12-20 22:46 UTC, funnell commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
since dupedist requires the version to know when to use 40 vs 2500, I suppose the thing to do is force HiSeq version numbers in the validation inputs

2022-12-20 22:50 UTC, nickp60 commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
Are they not?  The regex isn't pinned with ^<>$, so the idea is that the platform could be as vague as HiSeq but ideally should be specified with the model number as well.  Both should be valid

2022-12-20 22:52 UTC, nickp60 commented on config/config.yaml
> +dedup_platform: "HiSeq"
I'm wary of adding too many required config entries but this might be a good one to enforce.

2022-12-20 23:03 UTC, funnell commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
I interpreted this 

```dedup_platform:
     type: string
     default: true
     pattern: "(NextSeq|HiSeq|MiSeq|NovaSeq|SRA)"
```

as meaning exact match, but I could be wrong. 
if the platform version is meaningful (as it is for HiSeq) then we should require the HiSeq version number as part of the valid inputs. We want to avoid accepting invalid inputs (say a typo like HiSeq-3009)

2022-12-20 23:06 UTC, funnell commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
maybe `enum` is a better choice than pattern? https://json-schema.org/draft/2020-12/json-schema-validation.html#name-enum
I don't think I've tried it myself though

2022-12-22 17:03 UTC, nickp60 commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
Sorry, what exactly is the issue with this approach?  This seems to work as intended: this checks for the machine type or SRA, and then the dedup function checks to see if we have specifics that could be used to tune the deduplication parameters.
```
# Invalid platform
snakemake --snakefile workflow/Snakefile --profile /home/watersn/GitHub/vdblab-profile --rerun-incomplete --restart-times 0 --cores 32 --singularity-args '-B /home/watersn/GitHub/altshot,/data/brinkvd/' --directory tmppre/ --config sample=473 dedup_platform=HiSeq 'R1=[/data/brinkvd/data/shotgun/test/473/473_IGO_12587_1_S132_L003_R1_001.fastq.gz]' 'R2=[/data/brinkvd/data/shotgun/test/473/473_IGO_12587_1_S132_L003_R2_001.fastq.gz]' multiqc_config=/home/watersn/GitHub/altshot/multiqc_config.yaml nshards=2 kraken2_db=/data/brinkvd/watersn/minikraken2_v2_8GB_201904_UPDATE/ stage=preprocess dedup_platform="Hieq-2500"
Config file /lila/home/watersn/GitHub/altshot/workflow/../config/config.yaml is extended by additional config specified via the command line.
WorkflowError in file /lila/home/watersn/GitHub/altshot/workflow/Snakefile, line 20:
Error validating config file.
ValidationError: 'Hieq-2500' does not match '(NextSeq|HiSeq|MiSeq|NovaSeq|SRA)'

Failed validating 'pattern' in schema['properties']['dedup_platform']:
    OrderedDict([('type', 'string'),
                 ('default', True),
                 ('pattern', '(NextSeq|HiSeq|MiSeq|NovaSeq|SRA)')])

On instance['dedup_platform']:
    'Hieq-2500'
  File "/lila/home/watersn/GitHub/altshot/workflow/Snakefile", line 20, in <module>
  
  
  # but with valid platform:
   snakemake --snakefile workflow/Snakefile --profile /home/watersn/GitHub/vdblab-profile --rerun-incomplete --restart-times 0 --cores 32 --singul
arity-args '-B /home/watersn/GitHub/altshot,/data/brinkvd/' --directory tmppre/ --config sample=473 dedup_platform=HiSeq 'R1=[/data/brinkvd/data/shotgun/test/473/473_IGO_12587_1_S132_L003_R1_001.fastq.gz]
' 'R2=[/data/brinkvd/data/shotgun/test/473/473_IGO_12587_1_S132_L003_R2_001.fastq.gz]' multiqc_config=/home/watersn/GitHub/altshot/multiqc_config.yaml nshards=2 kraken2_db=/data/brinkvd/watersn/minikraken
2_v2_8GB_201904_UPDATE/ stage=preprocess dedup_platform="HiSeq-2500"
Config file /lila/home/watersn/GitHub/altshot/workflow/../config/config.yaml is extended by additional config specified via the command line.
localrules directive specifies rules that are not present in the Snakefile:
        hostdeplete_all

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 500
Conda environments: ignored
Job stats:
job                                  count    min threads    max threads
---------------------------------  -------  -------------  -------------
all                                      1              1              1
bowtie2_mouse                            2             24             24
bowtie_human                             2             24             24
bt_tally_depletion                       2              1              1
get_unmapped_human                       2              8              8
get_unmapped_human_mouse                 2              8              8
preprocess_bbmap_dedup                   1              8              8
preprocess_bbmap_run                     2              8              8
preprocess_cat_depletion_stats           1              1              1
preprocess_initial_fastqc_run            1              4              4
preprocess_merge_fastq_pair              1             16             16
preprocess_merge_logs_for_multiqc        1              1              1
preprocess_sortmerna_run                 2             16             16
snapalign_human                          2             24             24
snapalign_mouse                          2             24             24
utils_split_fastq                        1              4              4
total                                   25              1             24

Select jobs to execute...
  ```

2022-12-22 17:06 UTC, nickp60 commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
The pattern works as intended;  For example, the stage arg we require full matches so the pattern is pinned with `^<>$`. For instance tying to run stage=preprocess_all instead of the match "preprocess":
```
snakemake --snakefile workflow/Snakefile --profile /home/watersn/GitHub/vdblab-profile --rerun-incomplete --restart-times 0 --cores 32 --singularity-args '-B /home/watersn/GitHub/altshot,/data/brinkvd/' --directory tmppre/ --config sample=473 dedup_platform=HiSeq 'R1=[/data/brinkvd/data/shotgun/test/473/473_IGO_12587_1_S132_L003_R1_001.fastq.gz]' 'R2=[/data/brinkvd/data/shotgun/test/473/473_IGO_12587_1_S132_L003_R2_001.fastq.gz]' multiqc_config=/home/watersn/GitHub/altshot/multiqc_config.yaml nshards=2 kraken2_db=/data/brinkvd/watersn/minikraken2_v2_8GB_201904_UPDATE/ stage=preprocess_all dedup_platform="HiSeq-2500"
Config file /lila/home/watersn/GitHub/altshot/workflow/../config/config.yaml is extended by additional config specified via the command line.
WorkflowError in file /lila/home/watersn/GitHub/altshot/workflow/Snakefile, line 20:
Error validating config file.
ValidationError: 'preprocess_all' does not match '^(all|biobakery|preprocess|assembly|rgi|kraken|binning|annotate)$'

Failed validating 'pattern' in schema['properties']['stage']:
    OrderedDict([('type', 'string'),
                 ('pattern',
                  '^(all|biobakery|preprocess|assembly|rgi|kraken|binning|annotate)$')])

On instance['stage']:
    'preprocess_all'
  File "/lila/home/watersn/GitHub/altshot/workflow/Snakefile", line 20, in <module>
  ```

2022-12-22 22:11 UTC, funnell commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
what happens if you use HiSeq-1111?

2022-12-22 22:32 UTC, nickp60 commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
It runs as intended.  Because we don't have recommended deduplication parameters for an unknown sequencer, it runs with the default parameters.

2022-12-22 22:35 UTC, nickp60 commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
(to clarify, by "runs as intended", I mean that it passes the config schema and the output of the  `bbmap_dedup_params_dupedist` is the default of 40)

2022-12-22 22:53 UTC, funnell commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
But maybe we want to protect against that? If we want to allow unspecified platforms, then maybe we can have an "unknown" or "unspecified" option that would be explicitly set

2022-12-22 23:19 UTC, nickp60 commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
Lets add that for the future to-do's.  We have a million things to do right now and I don't want to delay this pr further by trying to catch all edge cases.  I'd be much happier to have stricter machine restrictions do this if we had the ideal bbmap/filtering parameters for all the sequencers but we don't. For our specific use case, Isabl already required specifying a valid sequencer type on metadata import.

2022-12-23 00:33 UTC, funnell commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
ok #24

2022-12-23 01:32 UTC, funnell commented
feel free to merge whenever you feel ready

2022-12-23 15:09 UTC, nickp60 commented on workflow/rules/common.smk
> +        elif config["dedup_platform"] == "HiSeq-3000":
Thanks; I want to be thorough but there are too many people asking me for results 😭 . I commented over at biostars asking about the ideal parameters for the missing platforms (MiSeq and MiniSeq).  I did notice a comment I overlooked with recommendations about when to use `spany` so I will incorporate that and merge.

2022-12-23 15:20 UTC, merged