Fix/hlatyping
vdblab/vdblab-shotgun pull request #44
Opened 2023-02-20 19:46 UTC by nickp60

This addresses issues #9, #25, and #28.  Jury is still out on #29.

Additionally, this removes the expectation for an HLA output in the preprocessing results.  Ancedotaly, with one abnormal sample having ~41M host reads (over 55% of the sample), the optityper scheme only recovered 263 HLA reads.  For normal stool samples the likelihood of having enough host reads to determine the HLA  type is very low.  

Because this is removing an output, I'm adding this as a pr for the 0.4.0 release

2023-02-21 21:16 UTC, funnell requested changes

2023-02-21 21:16 UTC, funnell commented on workflow/rules/HLA.smk
> +        razers3 -i 95 -m 1 -dr 0 -o {output.R1} {input.alleles} {input.R1}
should this be used?
```
[ -tc NUM ],  [ --thread-count NUM ]

  Use NUM threads (default: 1). Set to 0 to use the old RazerS 1/2 code path.
```
https://github.com/seqan/seqan/tree/master/apps/razers3

2023-02-21 21:16 UTC, funnell commented on workflow/rules/HLA.smk
> +    threads: 16
does samtools bam2fq have a threads option?

2023-02-23 20:47 UTC, nickp60 commented on workflow/rules/HLA.smk
> +        razers3 -i 95 -m 1 -dr 0 -o {output.R1} {input.alleles} {input.R1}
yes,thanks!

2023-02-23 20:48 UTC, nickp60 commented on workflow/rules/HLA.smk
> +    threads: 16
no; I have made the threads arg reflect that now.  thanks!

2023-02-23 20:48 UTC, merged